DATA_DIR: 'datasets/CIFAR-100'
LOG_DIR: 'checkpoint/logs'
CHECKPOINT: 'checkpoint'
SAVE_STEP: 5
VALID_STEP: 5
TRAIN:
  BATCH_SIZE: 128
  LR: 0.1
  EPOCH: 150
  DECAY_EPOCH: [30, 60, 80]
  LR_DECAY_GAMMA: 0.2
  WEIGHT_DECAY: 0.0005
  AUGMENTATION: True
TEST:
  BATCH_SIZE: 100
  AUGMENTATION: False